services:
  db:
    image: mongo
    restart: always
    command: ['--replSet', 'rs0']
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  mongo-init:
    image: mongo
    depends_on:
      - db
    restart: 'no'
    command:
      [
        'sh',
        '-c',
        'mongosh --host db:27017 --eval "try { rs.status() } catch (e) { rs.initiate({_id: \"rs0\", members: [{ _id: 0, host: \"db:27017\" }]}) }"',
      ]

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - db
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://db:27017/?replicaSet=rs0
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=root

  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    restart: always

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
      - WATCHPACK_POLLING=true
    depends_on:
      - db
      - mongo-init
      - redis
    ports:
      - '3000:3000'
    env_file:
      - .env

volumes:
  mongo-data:
  redis-data:
