apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  POSTGRES_USER: 'admin'
  POSTGRES_PASSWORD: 'rootpassword123'
  POSTGRES_DB: 'server_db'
  DATABASE_URL: 'postgresql://admin:rootpassword123@postgres-service:5432/server_db'
