export const CLS_KEYS = {
  USER: 'CURRENT_USER',
  DEMO_MEMBER: 'CURRENT_DEMO_MEMBER',
  DEPARTMENT_MEMBER: 'CURRENT_DEPARTMENT_MEMBER',
  DEMO_ID: 'DEMO_ID',
  DEPARTMENT_ID: 'DEPARTMENT_ID',
} as const;
